### ISSUE TITLE
Error en importación de librería com.javi:microservice-lib

### ISSUE THREAD

**Issue by miguelbriso** [javiorfo/java-spring3-microservice#2]
Buenos días:

Se produce un error porque no encuentra la librearía en Maven Central. ¿Podrías ayudarme para solucionarlo?

Tu proyecto me ha parecido muy interesante y me gustaría ponerme en contacto contigo para charlar sobre el proyecto.
¿Podrías facilitarme una cuenta de correo para que nos pongamos en contacto?

![image](https://github.com/user-attachments/assets/215410ec-ac91-4111-b669-7400a993f0ed)

Gracias por adelantado y,
un saludo.

**Comment by javiorfo** [comment]
Hola, @miguelbriso 

La librería the microservice-lib momentáneamente no está en maven-central. Tienes que bajartela como dice el README.
De todos modos te la paso por acá:
https://github.com/javiorfo/java-spring3-microservice-lib

Hay que ejecutar un `mvn clean install` primero en **java-spring3-microservice-lib** y luego en **java-spring3-microservice** así toma la librería de tu **.m2/repository**

Saludos
